tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'AdoptOpenJDK/openjdk'
tap 'clojure-lsp/brew'

# Development Tools
brew 'git'
brew 'cmake'
cask 'adoptopenjdk11'
brew 'leiningen'
brew 'clojure-lsp-native'
brew 'nvm'

# Editors
brew 'emacs'

# Fonts
cask 'font-hack'

# Security
cask 'keepassx'
cask 'yubico-authenticator'

# Applications
cask 'firefox'
cask 'slack'
cask 'spotify'

# Nucli dependencies
brew 'bash'
brew 'coreutils'
brew 'binutils'
brew 'diffutils'
brew 'ed'
brew 'findutils'
brew 'gawk'
brew 'gnu-indent'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnu-which'
brew 'gnutls'
brew 'grep'
brew 'gzip'
brew 'screen'
brew 'watch'
brew 'wget'
brew 'wdiff'
brew 'awscli'
brew 'jq'
brew 'node'
brew 'fzf'