tap 'homebrew/cask'
tap 'homebrew/cask-drivers'

# Development Tools
brew 'git'

# Editors
brew 'emacs'

# Security
cask 'keepassx'
cask 'yubico-authenticator'

# Applications
cask 'firefox'
cask 'slack'